language: node_js
services:
  - docker
#   Run all unit tests under the following environments
#   `npm test`
stage: "unit tests"
node_js:
  - "node"  # Latest
  - "lts/*" # Latest LTS
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
#   After and if all unit tests pass, run container test
#   `make start-test`
jobs:
  include:
    - stage: "container tests"
      name: "node-buster"
      #   `make start-test` will automatically build if images aren't found
      script: BUILD_TYPE=node-buster make start-test
    - stage: "container tests"
      name: "node-alpine"
      script: BUILD_TYPE=node-alpine make start-test
stages:
  - "unit tests"
  - "container tests"

