# docker-logentries

FROM mhart/alpine-node:5.10.1
LABEL maintainer="Rapid 7 - Logentries <support@logentries.com>"
RUN apk add --no-cache bash

WORKDIR /usr/src/app
COPY package.json index.js VERSION ./
RUN npm install --production && npm cache clean

ENTRYPOINT ["/usr/src/app/index.js"]
CMD []
